# Generated by Django 3.0.6 on 2020-05-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'contact_us',
                'db_table': 'contact_us',
            },
        ),
    ]
